let id = 0;

export const projects = {
  c: {
    libft: {
      id:(id += 1),
      name: 'libft',
      tags: ['c'],
      description: 'Part of libC',
      githubLink: '#',
      size: 1,
      dateOf: '',
      categorie: 'c',
    },
    get_next_line: {
      id:(id += 1),
      name: 'get_next_line',
      tags: ['c'],
      description: 'Like readline',
      githubLink: '#',
      size: 1,
      dateOf: '',
      categorie: 'c',
    },
    printf: {
      id:(id += 1),
      name: 'printf',
      tags: ['c'],
      description: 'Like printf',
      githubLink: '#',
      size: 2,
      dateOf: '',
      categorie: 'c',
    },
    sh: {
      id:(id += 1),
      name: '42sh',
      tags: ['c', 'unix'],
      description: 'A commande line interpreter & builtins (like Bash) with Tercamps Lib',
      githubLink: '#',
      size: 10,
      dateOf: '',
      categorie: 'c',
    },
    nmOtool: {
      id:(id += 1),
      name: 'nm/otool',
      tags: ['c', 'unix'],
      description: 'Like nm & otool command (nm: listing symbol of binary, otool: displays  specified  parts  of  object  files  or libraries)',
      githubLink: '#',
      size: 10,
      dateOf: '',
      categorie: 'c',
    },
  },

  python: {
    taskMaster: {
      id:(id += 1),
      name: 'Task Master',
      tags: ['python','unix'],
      description: 'Process gestionair like supervisor',
      githubLink: '#',
      size: 2,
      dateOf: '',
      categorie: 'python'
    },
    facebookTerminal: {
      id:(id += 1),
      name: 'Facebook Terminal',
      tags: ['python'],
      description: 'Basic fb python scrapper and message sender/checker',
      githubLink: '#',
      size: 2,
      dateOf: '',
      categorie: 'python'
    },
  },

  web: {
    roshambo: {
      id: (id += 1),
      name: 'Rock Paper Scissor',
      tags: ['react', 'javascript'],
      description: 'Rock paper scissor versus computer who select shape randomly',
      githubLink: '#',
      size: 2,
      dateOf: '',
      categorie: 'web',
    },
    marvelCatalog: {
      id: (id += 1),
      name: 'Marvel Catalog',
      tags: ['react', 'javascript'],
      description: 'Catalog of marvel Heroes with description',
      githubLink: '#',
      size: 2,
      dateOf: '',
      categorie: 'web',
    },
    todoList: {
      id: (id += 1),
      name: 'Todo list',
      tags: ['react', 'javascript', 'node'],
      description: 'Todo list with task and multi-user gestion with socket',
      githubLink: '#',
      size: 2,
      dateOf: '',
      categorie: 'web',
    },
  },

  security: {
    rootMeAppSystem: {
      id:(id += 1),
      name: 'Root me app/system',
      tags: ['c', 'unix', 'python', 'asm'],
      description: 'Series of challenge from plateform www.root-me.org in categorie App/system',
      githubLink: '#',
      size: 10,
      dateOf: '',
      categorie: 'security',
    },
    rootMeWeb: {
      id:(id += 1),
      name: 'Root me Web Server/Client',
      tags: ['javascript', 'php', 'webTools'],
      description: 'Series of challenge from plateform www.root-me.org in categorie web server and web client',
      githubLink: '#',
      size: 10,
      dateOf: '',
      categorie: 'security',
    },
    snowCrash: {
      id:(id += 1),
      name: 'SnowCrash',
      tags: ['unix', 'c', 'python', 'lua'],
      description: 'Series of challenge on VM. Get the flag level to level up',
      githubLink: '#',
      size: 10,
      dateOf: '',
      categorie: 'security',
    },
  },
};

export const tagColors = {
  c: 'orange',
  python: 'blue',
  unix: 'grey',
  react: 'red',
  javascript: 'yellow',
  node: 'purple',
  php: 'green',
  'html/css': 'pink',
  asm: 'lightgrey',
  lua: 'brown',
  webTools: 'wheat',
}

// phpPool: {
//       id: (id += 1),
//       name: 'PHP pool',
//       tags: ['php', 'html/css', 'javascript', 'sql'],
//       description: '2 weeks of web learning',
//       githubLink: '#',
//       size: 2,
//       dateOf: '',
//     },